SonarSource/sonar-scanner-npm

- README.md
- src/config.js
- test/unit/config.test.js
Implemented in #43. Cherry-picked their commit
> Add support for https proxy

- README.md
- src/config.js
- test/unit/config.test.js
> Add support for Basic authentication on SonarScanner mirrors

- package-lock.json
- package.json
- scripts/qa.sh
As per [CVE-2023-43646](https://www.mend.io/vulnerability-database/CVE-2023-43646), versions prior to 2.0.1 are vulnerable.
> Update chai version to fix vulnerability in transitive dependency get-func-name

- README.md
- src/config.js
- src/index.js
- src/sonar-scanner-executable.js
- test/unit/sonar-scanner-executable.test.js
Fixes https://github.com/SonarSource/sonar-scanner-npm/issues/45
> Add self-signed CA support

- tools/orchestrator/package-lock.json
- tools/orchestrator/package.json
Fixes #97 
There is a medium vulneribility in 1.15.4, let us update. We don't use this package explicitly, but only axios relies on it.
> Update follow-redirects to 1.15.6

- package-lock.json
- package.json
- src/constants.ts
- src/properties.ts
- src/scan.ts
- src/types.ts
- test/unit/fixtures/fake_project_with_sonar_properties_file/sonar-project.properties
- test/unit/mocks/FakeProjectMock.ts
- test/unit/properties.test.ts
> SCANNPM-10 Handle logic to process scanner properties from various sources with priority

- src/http-agent.ts
- src/java.ts
- src/properties.ts
- src/proxy.ts
- src/types.ts
- test/unit/http-agent.test.ts
- test/unit/java.test.ts
- test/unit/properties.test.ts
- test/unit/proxy.test.ts
This PR adds the ability to detect user-provided proxy configuration and creates http(s) agents passed to axios that will handle the proxy connection. 
Code is fully covered, but we'll need to do another validation at the end when we have the full flow working
> SCANNPM-14 Handle proxy detection & usage

- scripts/fix-comments.js
On the feature branch, `fix-comments.ts` fails when running `npm run build` with
```text
Error: EISDIR: illegal operation on a directory, read
```
Also for some reason `http-agent.js` and `types.js` are transpiled without the file header so I modified `fix-comments.ts` to always prepend the license even if it does not exist and fixed the error above
> SCANNPM-2 Fixup of fix-comments.ts

- src/constants.ts
- src/java.ts
- src/platform.ts
- src/properties.ts
- src/scan.ts
- src/types.ts
- test/unit/java.test.ts
- test/unit/mocks/FakeProjectMock.ts
- test/unit/platform.test.ts
- test/unit/properties.test.ts
- test/unit/scan.test.ts
- Fix min SQ version that supports JRE provisioning
- Fix hardcoded path to sonar cache folder in tests
- Fix newline parsing when trying to get sonar project files
- Make use of `sonar.scanner.os/arch` when provided by the user
> NPMSCAN-X Multi-fix bundle

- package-lock.json
- package.json
- src/config.js
- src/index.js
- src/sonar-scanner-executable.js
- test/unit/config.test.js
Fixes #113 
nothing from the env is being passed as arguments in the cmd, so we should be safe. Only cli args will be forwarded
> Enable `shell` on Windows

- src/request.ts
- src/scan.ts
- src/scanner-engine.ts
- src/types.ts
- test/unit/request.test.ts
- test/unit/scan.test.ts
- test/unit/scanner-engine.test.ts
- Support skipJreProvisioning property to skip JRE provisioning
- Support sonar.scanner.internal.dumpToFile properties
- Support sonar.scanner.responseTimeout properties
- Axios doesn’t support socketTimeout, so we can simply use responseTimeout in the bootstrapper
> SCANNPM-2 Add support for remaining properties

- src/constants.ts
- src/file.ts
- src/java.ts
- src/properties.ts
- src/request.ts
- src/scanner-engine.ts
- src/types.ts
- test/unit/file.test.ts
- test/unit/java.test.ts
- test/unit/properties.test.ts
- test/unit/request.test.ts
- test/unit/scanner-cli.test.ts
- test/unit/scanner-engine.test.ts
- test/unit/utils.test.js
[ticket](https://sonarsource.atlassian.net/browse/SCANNPM-25)
> SCANNPM-2 Use new endpoints & checksum/download logic & Do not use axios instance when fetching absolute URLs

- src/constants.ts
- src/java.ts
- src/process.ts
- src/properties.ts
- src/scan.ts
- src/scanner-cli.ts
- src/types.ts
- test/unit/java.test.ts
- test/unit/mocks/ChildProcessMock.ts
- test/unit/mocks/FakeProjectMock.ts
- test/unit/process.test.ts
- test/unit/properties.test.ts
- test/unit/scan.test.ts
- test/unit/scanner-cli.test.ts
[ticket](https://sonarsource.atlassian.net/browse/SCANNPM-31)
> SCANNPM-2 Change wasJreCacheHit from bool to enum and mark it disabled when skipping JRE provisioning explicitly

- src/properties.ts
- test/unit/fixtures/fake_project_with_package_and_sonar_properties/package.json
- test/unit/fixtures/fake_project_with_package_and_sonar_properties/sonar-project.properties
- test/unit/mocks/FakeProjectMock.ts
- test/unit/properties.test.ts
Kind of a follow-up of [this discussion](https://docs.google.com/document/d/1lmQzAHxsDTrBf2PyFa1aBJXvETX-ATznBHYPbZb115w/edit?disco=AAABNsX5ARQ). The priority we have is correct ( `sonar-project.properties` superseeds `package.json`) but the logic we inherited from the existing codebase can this be improvied/simplified. 
See [ticket](https://sonarsource.atlassian.net/browse/SCANNPM-35).
Making the change in the future version, targeting `feature/MMF-3712`, it's also a breaking change.
> SCANNPM-35 Change default values and logic for inferring package.json and sonar-project.properties

- README.md
- src/index.ts
Reintroduces the default export (callback-based) because we mention it in the README, so it's likely widely used all around.
> SCANNPM-8 Reintroduce default export

- README.md
Fix default README URL for `serverUrl`
> Fix default serverUrl value in README for v4

- .github/workflows/release.yml
- package-lock.json
- package.json
The release pipeline wasn't updated to build the package before releasing, meaning `v4.0.0` does not contain the `build` folder, which makes it impossible for users to use the `v4` at all.
> NO-JIRA Publish v4.0.1 & Fix release pipeline to include build folder

- src/constants.ts
- src/types.ts
- test/unit/properties.test.ts
Context:
https://community.sonarsource.com/t/unable-to-run-js-local-analysis-on-10-6/118997/9
https://sonarsource.atlassian.net/browse/SCANNPM-40
**Old Experience**
```
lucas.paulger@MAC0343 sonar-scanner-npm % sonar-scanner \
-Dsonar.sources=. \
-Dsonar.login=sqa_### \
-Dsonar.host.url=http://localhost:9000 \  -Dsonar.verbose=true \
-Dsonar.qualitygate.wait="true"
[INFO]  Bootstrapper: Retrieving info from "package.json" file
[DEBUG] Bootstrapper: Setting the log level to DEBUG due to verbose mode
[DEBUG] Bootstrapper: Properties: {
'sonar.scanner.os': 'darwin',
'sonar.scanner.arch': 'arm64',
...
'sonar.sources': '.',
'sonar.login': 'sqa_###',
'sonar.host.url': 'http://localhost:9000',
'sonar.verbose': 'true',
'sonar.scanner.internal.isSonarCloud': 'false',
'sonar.scanner.apiBaseUrl': …
```
> SCANNPM-40 Handle deprecated 'sonar.login' correctly

- src/properties.ts
- test/unit/fixtures/fake_project_with_basic_package_file/package.json
- test/unit/properties.test.ts
[ticket](https://sonarsource.atlassian.net/browse/SCANNPM-41)
Before this fix, running the NPM scanner with a package.json which did not contain a `name` entry would systematically crash the analysis. According to the user who reported this on community, it was introduced by V4.
> SCANNPM-41 Allow package.json not to contain a name entry

- .github/workflows/release.yml
- package.json
Fixes are in collaboration w/
https://sonarsource.atlassian.net/browse/BUILD-5492
The core changes are:
1. create a local directory to checkout the jfrog artifacts into
2. populates specific version information to be used in next steps
3. publishes to npm what was checked out into `steps.local_repo.outputs.dir` (see the dry-run example for what will be uploaded -> https://github.com/SonarSource/sonar-scanner-npm/actions/runs/10057370878/job/27798167415#step:9:3)
> NO-JIRA Fix release pipeline and promote jfrog artifact

- src/proxy.ts
- test/unit/proxy.test.ts
- test/unit/request.test.ts
See [ticket](https://sonarsource.atlassian.net/browse/SCANNPM-47) for context
> SCANNPM-47 Assume all proxies use http protocol

- .cirrus.star
- .cirrus.yml
[SCANNPM-56](https://sonarsource.atlassian.net/browse/SCANNPM-56)
Inspired by https://github.com/SonarSource/SonarJS/commit/8d7834cbecefc004f54541bec871ce1fde34d3ad
See also BUILD-6666
[SCANNPM-56]: https://sonarsource.atlassian.net/browse/SCANNPM-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANNPM-56 Remove deprecated CIRRUS_AWS_SUBNET

- src/request.ts
- test/unit/request.test.ts
Fixes [SCANNPM-58](https://sonarsource.atlassian.net/browse/SCANNPM-58) reported by [this user](https://community.sonarsource.com/t/npm-sonarqube-scanner-fails-behind-proxy/130094).
I chose to set `proxy: false` the closest to where we set the HTTP[S] agents in the code
[SCANNPM-58]: https://sonarsource.atlassian.net/browse/SCANNPM-58?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANNPM-58 Avoid conflicts between axios's proxy option and custom http(s) agents

- src/constants.ts
- src/properties.ts
- src/types.ts
- test/unit/file.test.ts
- test/unit/java.test.ts
- test/unit/mocks/FakeProjectMock.ts
- test/unit/properties.test.ts
- test/unit/scanner-engine.test.ts
This PR fixes 2 issues:
Described by this [ticket](https://sonarsource.atlassian.net/browse/SCANNPM-49):
- The default value set by the NPM Scanner is now `.scannerwork`, same as the Scanner CLI
- If a value is set by any mean, it will override this value
The path for archive extraction was different than the one for the CLI Scanner. Therefore, when:
- Cleaning the `.sonar` folder
- Analyzing a project with the CLI Scanner
- Analyzing a project with the NPM Scanner
The analysis failed because the NPM Scanner is looking for the extracted content in `~/.sonar/cache/{sha}/{filename}_extracted` where the CLI Scanner stored it in `~/.sonar/cache/{sha}/{filename}_unzip`. I've synchronized the value for both to `_unzip`.
> SCANNPM-49 Fix compatibility with other scanners (CLI, Scanner Engine)

- .github/workflows/PullRequestClosed.yml
- .github/workflows/PullRequestCreated.yml
- .github/workflows/RequestReview.yml
- .github/workflows/SubmitReview.yml
- .github/workflows/release.yml
[BUILD-8073](https://sonarsource.atlassian.net/browse/BUILD-8073)
Migrates public repository workflows from standard GitHub-hosted runners to **Large Runners**
(`ubuntu-latest` → `ubuntu-latest-large`, etc.).
See [BUILD-8073](https://sonarsource.atlassian.net/browse/BUILD-8073) for details.
[BUILD-8073]: https://sonarsource.atlassian.net/browse/BUILD-8073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BUILD-8073 Migrate public repositories workflows to large runners

- .github/workflows/PullRequestClosed.yml
- .github/workflows/PullRequestCreated.yml
- .github/workflows/RequestReview.yml
- .github/workflows/SubmitReview.yml
- .github/workflows/release.yml
[BUILD-8875](https://sonarsource.atlassian.net/browse/BUILD-8875)
This PR updates GitHub Actions workflows to use our new standardized runner naming convention.
- Updates runner names in workflow files to new standardized format
- No functional changes to your CI/CD pipelines
- All existing functionality remains identical
| Old Runner | New Runner |
|------------|------------|
| sonar-runner-large | github-ubuntu-latest-s |
| ubuntu-latest-large | github-ubuntu-latest-s |
| windows-latest-large | github-windows-latest-s |
| ubuntu-24.04-large | github-ubuntu-latest-s |
| sonar-runner-large-arm | github-ubuntu-24.04-arm-s |
| ubuntu-24.04-arm-large | github-ubuntu-24.04-arm-s |
1. Review the changes in this PR
2. Merge when ready - no additional action required
3. Old runners will remain …
> BUILD-8875: Migrate to standardized GitHub runner names
